name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 94.23.107.217
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/dataserv/ProjDataservComplet
            git pull origin main
            docker compose down
            docker compose up -d --build
